
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
live_config_reload = true

[colors.bright]
black = "#4d4d4d"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#ffffff"
yellow = "#ffffa5"

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.normal]
black = "#21222c"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[cursor.style]
blinking = "Never"

[font]
ligatures = true
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font Propo"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse.url]
launcher = "xdg-open"
mods = "None"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>'''

[window]
dynamic_title = true
history = 10000

[window.padding]
x = 2
y = 2

[keyboard]
